# Generated by Django 4.1.5 on 2023-02-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ordereditem_likeditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='likeditem',
            name='item_category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='likeditem',
            name='item_img',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='likeditem',
            name='item_name',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='likeditem',
            name='item_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='item_category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='item_img',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='item_name',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='item_price',
            field=models.FloatField(default=0.0),
        ),
    ]
