# Generated by Django 4.1.5 on 2023-02-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_likeditem_item_category_likeditem_item_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
